name: ERPMateus Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Publish Linux
        run: |
          dotnet publish ERPMateus/ERPMateus.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            -o publish-linux

      - name: Pack Linux
        run: |
          vpk pack \
          --packId ERPMateus \
          --packVersion ${GITHUB_REF_NAME#v} \
          --packDir publish-linux \
          --icon ERPMateus/Assets/icon.png \
          --channel linux \
          --outputDir ReleasesLinux

      - name: Upload Linux to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "ReleasesLinux/*"
          target: "/var/www/updates/erpmateus/linux"
          strip_components: 1



  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Publish Windows
        run: |
          dotnet publish ERPMateus/ERPMateus.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -o publish-win

      - name: Pack Windows
        run: |
          vpk pack `
          --packId ERPMateus `
          --packVersion ${env:GITHUB_REF_NAME.Replace('v','')} `
          --packDir publish-win `
          --icon ERPMateus/Assets/icon.png `
          --channel win `
          --outputDir ReleasesWin

      - name: Upload Windows to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "ReleasesWin/*"
          target: "/var/www/updates/erpmateus/win"
          strip_components: 1